// <auto-generated />
namespace Roland.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ImpactPrinterchangeDictionarywithHashSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImpactPrinterchangeDictionarywithHashSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201710142059260_ImpactPrinter change Dictionary with HashSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
